# docker-compose.yml

version: '3'

services:
  # Django service
  web:
    build: .
    commnad : python manage.py makemigrations  && python manage.py migrate && python manage.py runserver
    container_name: myapp
    ports:
      - "8000:8000"
    depends_on:
      - redis

  # Redis service
  redis:
    build:
      context: .
      dockerfile: DockerRedis
    ports:
      - "6379:6379"
